# Generated by Django 4.2.7 on 2023-11-06 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('research_id', models.AutoField(primary_key=True, serialize=False)),
                ('research_name', models.CharField(max_length=255)),
                ('db_host', models.CharField(max_length=255)),
                ('db_port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('algorithm_type', models.CharField(max_length=255)),
                ('research_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.researchproject')),
            ],
        ),
    ]
